version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydb
      - DB_PORT=3306

  db:
    image: "mysql:8.0"
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    volumes:
      - "db_data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

volumes:
  db_data:
